name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  committed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Lint commits
      uses: crate-ci/committed@master
  typos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Spell check
      uses: crate-ci/typos@master
